### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [norihiro/obs-h8819-source#12]
I know this plugin has so far been written for *nix, and the OBS resource page states "Currently this plugin is not provided for Windows".

What would be required to get it working on Windows - and, legitimately, **could I sponsor that development**?

I've been looking for some way to get REAC working in OBS for a *long* time, but we've got too much of a Windows-only software infrastructure for me to transition the stream PC to Linux. I would happily pay or contribute to make that a reality.

I've gotten REAC working in OBS using the official Roland driver in the past, but only on Windows versions 8.1 and older. The REAC driver was never updated for Windows 10 and no amount of hackery on my part has been able to get it working. An open source alternative would be amazing.

(We have an M200i and S1608, and also will soon be adding an S2416, if testing would be necessary/helpful)

**Comment by norihiro** [comment]
Thank you for interesting this plugin.
Major difficulties come from current implementation depending pcap library which is available on *nix system, and also I don't have Windows machine to test.

Steps I'm thinking to implement for Windows are something like below. 
- Use another library [npcap](https://npcap.com/) for Windows.
- Though major code can be shared, still need different implementation for some part.

Debugging is also welcome as I don't have Windows machine for testing REAC.

**Comment by norihiro** [comment]
Hi @Yttrium-tYcLief,

Could you test this preliminary version?
1. Install npcap library. [Instruction is here.](https://github.com/norihiro/obs-h8819-source/wiki/Install-Npcap)
2. Download and install this package. [obs-h8819-source-dbebc22-obs27-Windows.zip](https://github.com/norihiro/obs-h8819-source/files/9599420/obs-h8819-source-dbebc22-obs27-Windows.zip)

**Comment by Yttrium-tYcLief** [comment]
Apologies for the slow response - unfortunately due to the nature of the environment, I only tend to have physical access on Sundays. I will be sure to test the provided version when I'm next there (tomorrow)!

**Comment by norihiro** [comment]
No problem. Please take your time.

**Comment by Yttrium-tYcLief** [comment]
Unfortunately the plugin causes OBS to crash when started. It didn't crash the first time, it started crashing when adding the REAC audio source.

Even after removing the source from the scene, though, OBS continued to crash on startup until the plugin was completely removed.

I'm going to debug a little bit later, after I run the necessary shows today.

**Comment by Yttrium-tYcLief** [comment]
[2022-09-25 09-26-43.txt](https://github.com/norihiro/obs-h8819-source/files/9640860/2022-09-25.09-26-43.txt)
[Crash 2022-09-25 09-26-45.txt](https://github.com/norihiro/obs-h8819-source/files/9640862/Crash.2022-09-25.09-26-45.txt)

forgot to attach logs

EDIT: Reading the log in some downtime, looks like it can't find the npcap driver. Might have needed to restart after installing npcap, but too late now and can't during a show. Will test more soon.

**Comment by norihiro** [comment]
Thank you for testing. I have updated the code. This should be ok.
[obs-h8819-source-6e167d7-obs27-Windows.zip](https://github.com/norihiro/obs-h8819-source/files/9640929/obs-h8819-source-6e167d7-obs27-Windows.zip)

I was testing with already-configured settings but newly created source, which has empty settings internally, and the crash was reproduced.

**Comment by Yttrium-tYcLief** [comment]
Sounds good - will test the new version shortly. I'll be in this environment for most of the day, so we can rapidly iterate if need be.

**Comment by Yttrium-tYcLief** [comment]
It's working. It should be noted somewhere that the channels selected are for REAC *outputs*, not *inputs*, but yes, it's definitely working. At least, I see the levels are working. They're a bit lower than expected, but it's fully digital so I should be able to increase the gain without artifacts.

I haven't actually listened to the audio feed yet - working on testing that now. But looking good so far!

**Comment by norihiro** [comment]
I'm glad to hear that.
Log will show if there was dropped frames for roughly every minutes. Please test with loaded condition and check it before you use it on your productions. Especially camera input and recording/streaming will consume data transfer between peripherals and CPU so that this plugin's audio might be affected.

It's midnight on my timezone. My response will be slow later.

**Comment by norihiro** [comment]
I'm sorry, I accidentally clicked the close button. This ticket will be closed later when the PR is merged and ready for new release.

**Comment by Yttrium-tYcLief** [comment]
> I'm sorry, I accidentally clicked the close button.

No worries!

I'll be stress testing it all day. With a completely separate network adapter and VLAN, it shouldn't impact any of the network aspects of the production, but I'll certainly pay close attention to frame render times and the like.

**Comment by norihiro** [comment]
I've created a [release 0.3.0](https://github.com/norihiro/obs-h8819-source/releases/tag/0.3.0). Please feel free to reopen this ticket if something is wrong.
